// src/lib/calculator-components/ResultDisplay.svelte
<script >
    import { resValue } from "../stores";
    const defaultLabelName = "grid grid-flow-col justify-center text-2xl"
</script>



<div id="result-container" class="h-48 translate-y-1/4">
    <div id="result" class="grid grid-flow-col justify-center text-5xl font-bold my-5 gap-4 top-5">{$resValue}</div>
    <div id="result-label" class={defaultLabelName }>{$resValue? 'containers' : ''}</div>
</div>

// app/components/ResultDisplay.tsx
'use client'

import React, { useEffect, useState } from "react";

export const defaultLabelName = "grid grid-flow-col justify-center text-2xl "

const ResultDisplay = () => {
    const [hasMounted, setHasMounted] = useState(false);

    
    useEffect(() => {
        setHasMounted(true);
    }, [])

    if (!hasMounted) {
        return null;
    }

    return (
        <div id="result-container" className="h-48 translate-y-1/4">
            <div id="result" className="grid grid-flow-col justify-center text-5xl font-bold my-5 gap-4 top-5"></div>
            <div id="result-label" className={defaultLabelName + "invisible"}>containers</div>
        </div>
    );
};


export default ResultDisplay;
