// app/components/InputBoxes.tsx
'use client'

import React, { useEffect, useState } from "react";

const boxes = [
    {
        id: 'ttd',
        placeholder: 'Total Daily Dose',
        units: 'units per day'
    },
    {
        id: 'days',
        placeholder: 'Number of Days',
        units: '30, 60, etc.'
    },
    {
        id: 'insulin-dispense',
        placeholder: 'Insulin Dispensed',
        units: 'units/container'
    },
]

export const defaultBoxName = "input input-bordered input-info"

const InputBoxes = () => {
    const [hasMounted, setHasMounted] = useState(false);

    useEffect(() => {
        setHasMounted(true);
    }, [])

    if (!hasMounted) {
        return null;
    }

    return (
        <div className="grid justify-center self-center gap-10 ">
            {   // map over the box data and create input boxes in column order
                boxes.map(({id, placeholder, units}) => {
                    return (
                            <div id={id+'_'} className="grid">
                                <input id={id} type="text" placeholder={placeholder} 
                                    className={defaultBoxName} />

                                <span className="label-text grid justify-end">{units}</span>
                            </div>
                    )
                })
            }
        </div>
    );
};


export default InputBoxes

// src/lib/calculator-components/InputBoxes.svelte
<script context="module">
    let boxes = [
        {
            id: 'ttd',
            placeholder: 'Total Daily Dose',
            units: 'units/day'
        },
        {
            id: 'days',
            placeholder: 'Number of Days',
            units: '30, 60, etc.'
        },
        {
            id: 'insulin-strength',
            placeholder: 'Insulin Strength',
            units: 'u-100, 200, etc'
        },
        {
            id: 'insulin-dispense',
            placeholder: 'Insulin Amount',
            units: 'mL/container'
        },
    ]
    export let defaultBoxClass = "input input-bordered input-info input-lg"
</script>

<div class="grid justify-center self-center gap-10 ">
    {#each boxes as box}
        <div class="grid">
            <input id={box.id} type="text" placeholder={box.placeholder} 
                class={defaultBoxClass} />
            <span class="label-text grid justify-end">{box.units}</span>
        </div>
    {/each}
</div>
